# Generated by Django 3.1.2 on 2020-10-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201006_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
